GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTkzNDI4NDEsImV4cCI6MTY5OTM0NjQ0MSwiYXVkIjoiNjU0ODhiYTk1NGY4YWJmMDZlYjM1OThmIiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.HuwriFEi0CSQZCpz2aHs3y1HCOTQuviTTr7UReYa5to

###Login Route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "bola20019@gmail.com",
    "password" : "122fs"
}


###Register Route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email" : "bola20019@gmail.com",
    "password" : "122fs"
}


###Refresh-token Route
POST http://localhost:3000/auth/refresh-token


###Logout Route
DELETE  http://localhost:3000/auth/logout




